name: GitHub Actions Parallel Run
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
   
jobs:
  Firefox-Test:
    strategy:
      matrix:
       version: [ 10, 12]
       os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on:  ${{ matrix.os}}
        steps:
         - uses: actions/setup-node@v3
           with:
            node-version: ${{ matrix.version }}
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:firefox
          browser: chrome
          headless: true
          record: false
  Chrome-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:chrome
          browser: chrome
          headless: true
          record: false