name: GitHub Actions Parallel Run
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
   
jobs:
  Google-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:firefox
          browser: chrome
          headless: true
          record: false
  Amazon-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:chrome
          browser: chrome
          headless: true
          record: false