name: GitHub Actions Parallel Run
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
   
jobs:
  Firefox-Test:
    strategy:
      matrix:
       version: [ 10, 12, 14 ]
       os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:firefox
          browser: chrome
          headless: true
          record: false
  Chrome-Test:
    strategy:
      matrix:
       version: [ 10, 12, 14 ]
       os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:chrome
          browser: chrome
          headless: true
          record: false