name: GitHub Actions Parallel Run
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
   
jobs:
  Firefox-Test:
    strategy:
      fail-fast: false
      matrix:
       containers: [1, 2, 3] 
       version: [ 10, 12, 14 ]
       os: [ ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:firefox
          browser: chrome
          headless: true
          record: true
          parallel: true
      - name: Upload Report- Firefox
        uses: actions/upload-artifact@v3
        with:
         name: Test-Report-Firefox
         path: cypress/reports/Result
          
      -  name: Upload merged artifact  
         uses: actions/download-artifact@v3
         with:
           path: cypress/reports/

  Chrome-Test:
    strategy:
      matrix:
       version: [ 10, 12, 14 ]
       os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: e2e
        uses: cypress-io/github-action@v6
        with:
          command: npm run cy:run:chrome
          browser: chrome
          headless: true
          record: true
          parallel: true
      - name: Upload Report- Chrome
        uses: actions/upload-artifact@v3
        with:
            name: Test-Report-Chrome
            path: cypress/reports/Result
            
      - name: Upload merged artifact  
        uses: actions/download-artifact@v3
        with:
           path: cypress/reports/
           
      - name : Merger 
        run: cp cypress/reports/Test-Report-*/* > cypress/reports/merged-report | cat cypress/reports/merged-report/*.html > cypress/reports/finalReport.html    